---
- hosts: all
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
#      when: ansible_os_family == 'Debian'
- hosts: all
  gather_facts: false
  tasks:
    - meta: clear_host_errors
