---
- hosts: all
  roles:
    - Apache
<<<<<<< HEAD
  #  - acesso_remoto
  #  - fonte_garamound
#    - role: geerlingguy.ntp
  #    ntp_timezone: America/Sao_Paulo
  #    ntp_manage_config: true
  #    ntp_servers:
  #      - "pool.ntp.br iburst"
  #      - "ntp.cais.rnp.br iburst"
=======
>>>>>>> b4ca12cf21975dbcb3162fac08169025b3d631fd
